#' ploswater: A dataset of papers from PLOS Water journal
#'
#' This dataset includes data on papers published in the PLOS Water journal. All raw data is obtained using the OpenAlex API.
#' The data includes details on the publication, references, authorship, and institutions.
#'
#' @format A tibble with 240 rows and 1506 variables
#' \describe{
#'   \item{id}{Unique Identifier}
#'   \item{doi}{DOI of the study}
#'   \item{title}{Title of the study}
#'   \item{display_name}{Displayed Name in OpenAlex}
#'   \item{publication_year}{Year of publication}
#'   \item{publication_date}{Date of publication}
#'   \item{language}{Original publication language}
#'   \item{type}{Indicates the type of scholarly work}
#'   \item{type_crossref}{The work type as specified by Crossref}
#'   \item{indexed_in}{}
#'   \item{authorships}{Contains detailed information about authors and their institutional affiliations}
#'   \item{institution_assertions}{Information about institutional affiliations}
#'   \item{countries_distinct_count}{Total number of unique country codes among the work's authorships}
#'   \item{institutions_distinct_count}{Total number of unique institutions among the work's authorships}
#'   \item{corresponding_author_ids}{List of OpenAlex IDs for corresponding authors}
#'   \item{corresponding_institution_ids}{List of OpenAlex IDs for institutions of corresponding authors}
#'   \item{fwci}{Field-weighted Citation Impact, calculated as the ratio of citations received to citations expected in the publication year and three following years}
#'   \item{has_fulltext}{Boolean indicating if the full text is searchable in OpenAlex}
#'   \item{fulltext_origin}{Indicates how the full text was obtained (e.g., "pdf" or "ngrams") when has_fulltext is true}
#'   \item{cited_by_count}{Number of times the work has been cited}
#'   \item{is_retracted}{Wether study was retracted or not}
#'   \item{is_paratext}{}
#'   \item{topics}{}
#'   \item{keywords}{Keywords in the text}
#'   \item{concepts}{Key concepts in the text}
#'   \item{mesh}{}
#'   \item{locations_count}{Number of different places where the work can be found}
#'   \item{locations}{List of all places where the work exists, including journals, proceedings, repositories (like arXiv), and institutional repositories}
#'   \item{sustainable_development_goals}{Classifications linking the work to UN Sustainable Development Goals (SDGs)}
#'   \item{grants}{Information about research funding and grants associated with the work}
#'   \item{datasets}{Associated research datasets}
#'   \item{versions}{Different versions of the work available across locations (e.g., peer-reviewed published version, preprint version)}
#'   \item{referenced_works_count}{Number of works this work cites}
#'   \item{referenced_works}{List of works cited by this work}
#'   \item{related_works}{Works that are related to this one}
#'   \item{cited_by_api_url}{URL to access the list of works citing this work}
#'   \item{counts_by_year}{Year-by-year breakdown of citation counts, excluding citations older than ten years}
#'   \item{updated_date}{ISO 8601 date string showing when the record was last modified}
#'   \item{created_date}{ISO 8601 date string indicating when the work was first added to OpenAlex}
#'   \item{ids.openalex}{The primary identifier in OpenAlex}
#'   \item{ids.doi}{The Digital Object Identifier, serving as the Canonical External ID}
#'   \item{primary_location.is_oa}{}
#'   \item{primary_location.landing_page_url}{}
#'   \item{primary_location.pdf_url}{}
#'   \item{primary_location.license}{}
#'   \item{primary_location.license_id}{}
#'   \item{primary_location.version}{}
#'   \item{primary_location.is_accepted}{}
#'   \item{primary_location.is_published}{}
#'   \item{primary_location.source.id}{}
#'   \item{primary_location.source.display_name}{}
#'   \item{primary_location.source.issn_l}{}
#'   \item{primary_location.source.issn}{}
#'   \item{primary_location.source.is_oa}{}
#'   \item{primary_location.source.is_in_doaj}{}
#'   \item{primary_location.source.is_core}{}
#'   \item{primary_location.source.host_organization}{}
#'   \item{primary_location.source.host_organization_name}{}
#'   \item{primary_location.source.host_organization_lineage}{}
#'   \item{primary_location.source.host_organization_lineage_names}{}
#'   \item{primary_location.source.type}{}
#'   \item{open_access.is_oa}{}
#'   \item{open_access.oa_status}{}
#'   \item{open_access.oa_url}{}
#'   \item{open_access.any_repository_has_fulltext}{}
#'   \item{apc_list.value}{}
#'   \item{apc_list.currency}{}
#'   \item{apc_list.value_usd}{}
#'   \item{apc_list.provenance}{}
#'   \item{apc_paid.value}{}
#'   \item{apc_paid.currency}{}
#'   \item{apc_paid.value_usd}{}
#'   \item{apc_paid.provenance}{}
#'   \item{citation_normalized_percentile.value}{}
#'   \item{citation_normalized_percentile.is_in_top_1_percent}{}
#'   \item{citation_normalized_percentile.is_in_top_10_percent}{}
#'   \item{cited_by_percentile_year.min}{}
#'   \item{cited_by_percentile_year.max}{}
#'   \item{biblio.volume}{}
#'   \item{biblio.issue}{}
#'   \item{biblio.first_page}{}
#'   \item{biblio.last_page}{}
#'   \item{primary_topic.id}{}
#'   \item{primary_topic.display_name}{}
#'   \item{primary_topic.score}{}
#'   \item{primary_topic.subfield.id}{}
#'   \item{primary_topic.subfield.display_name}{}
#'   \item{primary_topic.field.id}{}
#'   \item{primary_topic.field.display_name}{}
#'   \item{primary_topic.domain.id}{}
#'   \item{primary_topic.domain.display_name}{}
#'   \item{best_oa_location.is_oa}{}
#'   \item{best_oa_location.landing_page_url}{}
#'   \item{best_oa_location.pdf_url}{}
#'   \item{best_oa_location.license}{}
#'   \item{best_oa_location.license_id}{}
#'   \item{best_oa_location.version}{}
#'   \item{best_oa_location.is_accepted}{}
#'   \item{best_oa_location.is_published}{}
#'   \item{best_oa_location.source.id}{}
#'   \item{best_oa_location.source.display_name}{}
#'   \item{best_oa_location.source.issn_l}{}
#'   \item{best_oa_location.source.issn}{}
#'   \item{best_oa_location.source.is_oa}{}
#'   \item{best_oa_location.source.is_in_doaj}{}
#'   \item{best_oa_location.source.is_core}{}
#'   \item{best_oa_location.source.host_organization}{}
#'   \item{best_oa_location.source.host_organization_name}{}
#'   \item{best_oa_location.source.host_organization_lineage}{}
#'   \item{best_oa_location.source.host_organization_lineage_names}{}
#'   \item{best_oa_location.source.type}{}
#'   \item{abstract_inverted_index.water}{}
#'   \item{abstract_inverted_index.and}{}
#'   \item{abstract_inverted_index.sanitation}{}
#'   \item{abstract_inverted_index.programs}{}
#'   \item{abstract_inverted_index.have}{}
#'   \item{abstract_inverted_index.focused}{}
#'   \item{abstract_inverted_index.on}{}
#'   \item{abstract_inverted_index.value}{}
#'   \item{abstract_inverted_index.in}{}
#'   \item{abstract_inverted_index.improving}{}
#'   \item{abstract_inverted_index.conditions}{}
#'   \item{abstract_inverted_index.evidence}{}
#'   \item{abstract_inverted_index.This}{}
#'   \item{abstract_inverted_index.review}{}
#'   \item{abstract_inverted_index.identified}{}
#'   \item{abstract_inverted_index.empirical}{}
#'   \item{abstract_inverted_index.research}{}
#'   \item{abstract_inverted_index.that}{}
#'   \item{abstract_inverted_index.and/or}{}
#'   \item{abstract_inverted_index.reported}{}
#'   \item{abstract_inverted_index.used,}{}
#'   \item{abstract_inverted_index.methods}{}
#'   \item{abstract_inverted_index.if}{}
#'   \item{abstract_inverted_index.was}{}
#'   \item{abstract_inverted_index.the}{}
#'   \item{abstract_inverted_index.A}{}
#'   \item{abstract_inverted_index.conceptual}{}
#'   \item{abstract_inverted_index.model}{}
#'   \item{abstract_inverted_index.of}{}
#'   \item{abstract_inverted_index.which}{}
#'   \item{abstract_inverted_index.includes}{}
#'   \item{abstract_inverted_index.three}{}
#'   \item{abstract_inverted_index.resources,}{}
#'   \item{abstract_inverted_index.institutional}{}
#'   \item{abstract_inverted_index.analysis.}{}
#'   \item{abstract_inverted_index.We}{}
#'   \item{abstract_inverted_index.Global}{}
#'   \item{abstract_inverted_index.for}{}
#'   \item{abstract_inverted_index.peer-reviewed}{}
#'   \item{abstract_inverted_index.sources}{}
#'   \item{abstract_inverted_index.either}{}
#'   \item{abstract_inverted_index.related}{}
#'   \item{abstract_inverted_index.terms}{}
#'   \item{abstract_inverted_index.from}{}
#'   \item{abstract_inverted_index.were}{}
#'   \item{abstract_inverted_index.representing}{}
#'   \item{abstract_inverted_index.over}{}
#'   \item{abstract_inverted_index.used}{}
#'   \item{abstract_inverted_index.followed}{}
#'   \item{abstract_inverted_index.framework}{}
#'   \item{abstract_inverted_index.analysis}{}
#'   \item{abstract_inverted_index.approach,}{}
#'   \item{abstract_inverted_index.using}{}
#'   \item{abstract_inverted_index.as}{}
#'   \item{abstract_inverted_index.two}{}
#'   \item{abstract_inverted_index.additional}{}
#'   \item{abstract_inverted_index.relevant}{}
#'   \item{abstract_inverted_index.to}{}
#'   \item{abstract_inverted_index.The}{}
#'   \item{abstract_inverted_index.majority}{}
#'   \item{abstract_inverted_index.or}{}
#'   \item{abstract_inverted_index.published}{}
#'   \item{abstract_inverted_index.since}{}
#'   \item{abstract_inverted_index.proportion}{}
#'   \item{abstract_inverted_index.studies}{}
#'   \item{abstract_inverted_index.half}{}
#'   \item{abstract_inverted_index.yet}{}
#'   \item{abstract_inverted_index.only}{}
#'   \item{abstract_inverted_index.provided}{}
#'   \item{abstract_inverted_index.a}{}
#'   \item{abstract_inverted_index.least}{}
#'   \item{abstract_inverted_index.assessing}{}
#'   \item{abstract_inverted_index.are}{}
#'   \item{abstract_inverted_index.is}{}
#'   \item{abstract_inverted_index.main}{}
#'   \item{abstract_inverted_index.more}{}
#'   \item{abstract_inverted_index.approaches}{}
#'   \item{abstract_inverted_index.reduce}{}
#'   \item{abstract_inverted_index.systemic}{}
#'   \item{abstract_inverted_index.resources}{}
#'   \item{abstract_inverted_index.For}{}
#'   \item{abstract_inverted_index.first}{}
#'   \item{abstract_inverted_index.time}{}
#'   \item{abstract_inverted_index.has}{}
#'   \item{abstract_inverted_index.been}{}
#'   \item{abstract_inverted_index.focus}{}
#'   \item{abstract_inverted_index.both}{}
#'   \item{abstract_inverted_index.2}{}
#'   \item{abstract_inverted_index.we}{}
#'   \item{abstract_inverted_index.argue}{}
#'   \item{abstract_inverted_index.here}{}
#'   \item{abstract_inverted_index.not}{}
#'   \item{abstract_inverted_index.attention}{}
#'   \item{abstract_inverted_index.it}{}
#'   \item{abstract_inverted_index.scientists}{}
#'   \item{abstract_inverted_index.policymakers}{}
#'   \item{abstract_inverted_index.several}{}
#'   \item{abstract_inverted_index.historical}{}
#'   \item{abstract_inverted_index.temperature}{}
#'   \item{abstract_inverted_index.change}{}
#'   \item{abstract_inverted_index.further}{}
#'   \item{abstract_inverted_index.increased}{}
#'   \item{abstract_inverted_index.with}{}
#'   \item{abstract_inverted_index.use}{}
#'   \item{abstract_inverted_index.global}{}
#'   \item{abstract_inverted_index.levels}{}
#'   \item{abstract_inverted_index.by}{}
#'   \item{abstract_inverted_index.an}{}
#'   \item{abstract_inverted_index.aim}{}
#'   \item{abstract_inverted_index.be}{}
#'   \item{abstract_inverted_index.consistent}{}
#'   \item{abstract_inverted_index.current}{}
#'   \item{abstract_inverted_index.policy}{}
#'   \item{abstract_inverted_index.increasing}{}
#'   \item{abstract_inverted_index.extreme}{}
#'   \item{abstract_inverted_index.weather}{}
#'   \item{abstract_inverted_index.sometimes}{}
#'   \item{abstract_inverted_index.changes}{}
#'   \item{abstract_inverted_index.such}{}
#'   \item{abstract_inverted_index.land}{}
#'   \item{abstract_inverted_index.variability}{}
#'   \item{abstract_inverted_index.cycle}{}
#'   \item{abstract_inverted_index.season}{}
#'   \item{abstract_inverted_index.season,}{}
#'   \item{abstract_inverted_index.year}{}
#'   \item{abstract_inverted_index.also}{}
#'   \item{abstract_inverted_index.impacts}{}
#'   \item{abstract_inverted_index.all}{}
#'   \item{abstract_inverted_index.needed}{}
#'   \item{abstract_inverted_index.understanding}{}
#'   \item{abstract_inverted_index.effectiveness}{}
#'   \item{abstract_inverted_index.future}{}
#'   \item{abstract_inverted_index.adaptation}{}
#'   \item{abstract_inverted_index.strategies}{}
#'   \item{abstract_inverted_index.reducing}{}
#'   \item{abstract_inverted_index.water-related}{}
#'   \item{abstract_inverted_index.climate}{}
#'   \item{abstract_inverted_index.Finally,}{}
#'   \item{abstract_inverted_index.role}{}
#'   \item{abstract_inverted_index.assessment}{}
#'   \item{abstract_inverted_index.require}{}
#'   \item{abstract_inverted_index.whose}{}
#'   \item{abstract_inverted_index.feasibility}{}
#'   \item{abstract_inverted_index.efficiency}{}
#'   \item{abstract_inverted_index.resources.}{}
#'   \item{abstract_inverted_index.It}{}
#'   \item{abstract_inverted_index.thus}{}
#'   \item{abstract_inverted_index.essential}{}
#'   \item{abstract_inverted_index.develop}{}
#'   \item{abstract_inverted_index.integrated}{}
#'   \item{abstract_inverted_index.approach}{}
#'   \item{abstract_inverted_index.change,}{}
#'   \item{abstract_inverted_index.would}{}
#'   \item{abstract_inverted_index.between}{}
#'   \item{abstract_inverted_index.hydrological}{}
#'   \item{abstract_inverted_index.testing}{}
#'   \item{abstract_inverted_index.novel}{}
#'   \item{abstract_inverted_index.tool}{}
#'   \item{abstract_inverted_index.public}{}
#'   \item{abstract_inverted_index.health}{}
#'   \item{abstract_inverted_index.monitoring,}{}
#'   \item{abstract_inverted_index.but}{}
#'   \item{abstract_inverted_index.laboratory}{}
#'   \item{abstract_inverted_index.capacity}{}
#'   \item{abstract_inverted_index.provide}{}
#'   \item{abstract_inverted_index.monitoring}{}
#'   \item{abstract_inverted_index.at}{}
#'   \item{abstract_inverted_index.locations}{}
#'   \item{abstract_inverted_index.where}{}
#'   \item{abstract_inverted_index.potential}{}
#'   \item{abstract_inverted_index.practices}{}
#'   \item{abstract_inverted_index.wastewater}{}
#'   \item{abstract_inverted_index.currently}{}
#'   \item{abstract_inverted_index.quality}{}
#'   \item{abstract_inverted_index.control}{}
#'   \item{abstract_inverted_index.may}{}
#'   \item{abstract_inverted_index.across}{}
#'   \item{abstract_inverted_index.many}{}
#'   \item{abstract_inverted_index.academic}{}
#'   \item{abstract_inverted_index.out}{}
#'   \item{abstract_inverted_index.Here,}{}
#'   \item{abstract_inverted_index.our}{}
#'   \item{abstract_inverted_index.including}{}
#'   \item{abstract_inverted_index.standard}{}
#'   \item{abstract_inverted_index.operating}{}
#'   \item{abstract_inverted_index.present}{}
#'   \item{abstract_inverted_index.data}{}
#'   \item{abstract_inverted_index.discuss}{}
#'   \item{abstract_inverted_index.reporting}{}
#'   \item{abstract_inverted_index.this}{}
#'   \item{abstract_inverted_index.information}{}
#'   \item{abstract_inverted_index.will}{}
#'   \item{abstract_inverted_index.others}{}
#'   \item{abstract_inverted_index.developing}{}
#'   \item{abstract_inverted_index.support}{}
#'   \item{abstract_inverted_index.decision-making.}{}
#'   \item{abstract_inverted_index.agriculture}{}
#'   \item{abstract_inverted_index.significant}{}
#'   \item{abstract_inverted_index.food}{}
#'   \item{abstract_inverted_index.socio-economic}{}
#'   \item{abstract_inverted_index.people}{}
#'   \item{abstract_inverted_index.living}{}
#'   \item{abstract_inverted_index.some}{}
#'   \item{abstract_inverted_index.UN}{}
#'   \item{abstract_inverted_index.Organization}{}
#'   \item{abstract_inverted_index.(e.g.,}{}
#'   \item{abstract_inverted_index.World}{}
#'   \item{abstract_inverted_index.River}{}
#'   \item{abstract_inverted_index.these}{}
#'   \item{abstract_inverted_index.areas}{}
#'   \item{abstract_inverted_index.resource}{}
#'   \item{abstract_inverted_index.sustainability}{}
#'   \item{abstract_inverted_index.its}{}
#'   \item{abstract_inverted_index.unique}{}
#'   \item{abstract_inverted_index.risk}{}
#'   \item{abstract_inverted_index.process}{}
#'   \item{abstract_inverted_index.results}{}
#'   \item{abstract_inverted_index.multiple}{}
#'   \item{abstract_inverted_index.natural}{}
#'   \item{abstract_inverted_index.recently}{}
#'   \item{abstract_inverted_index.river}{}
#'   \item{abstract_inverted_index.sustainable}{}
#'   \item{abstract_inverted_index.development}{}
#'   \item{abstract_inverted_index.particularly}{}
#'   \item{abstract_inverted_index.lack}{}
#'   \item{abstract_inverted_index.leads}{}
#'   \item{abstract_inverted_index.discharge}{}
#'   \item{abstract_inverted_index.flow}{}
#'   \item{abstract_inverted_index.agricultural}{}
#'   \item{abstract_inverted_index.plant}{}
#'   \item{abstract_inverted_index.uptake}{}
#'   \item{abstract_inverted_index.effects}{}
#'   \item{abstract_inverted_index.crop}{}
#'   \item{abstract_inverted_index.growth}{}
#'   \item{abstract_inverted_index.higher}{}
#'   \item{abstract_inverted_index.lower}{}
#'   \item{abstract_inverted_index.soil}{}
#'   \item{abstract_inverted_index.microbial}{}
#'   \item{abstract_inverted_index.activity,}{}
#'   \item{abstract_inverted_index.overall}{}
#'   \item{abstract_inverted_index.case}{}
#'   \item{abstract_inverted_index.critical}{}
#'   \item{abstract_inverted_index.regions}{}
#'   \item{abstract_inverted_index.can}{}
#'   \item{abstract_inverted_index.considered}{}
#'   \item{abstract_inverted_index.possible}{}
#'   \item{abstract_inverted_index.Two}{}
#'   \item{abstract_inverted_index.among}{}
#'   \item{abstract_inverted_index.home}{}
#'   \item{abstract_inverted_index.animal}{}
#'   \item{abstract_inverted_index.strong}{}
#'   \item{abstract_inverted_index.rural}{}
#'   \item{abstract_inverted_index.major}{}
#'   \item{abstract_inverted_index.area}{}
#'   \item{abstract_inverted_index.important}{}
#'   \item{abstract_inverted_index.hydraulic}{}
#'   \item{abstract_inverted_index.works}{}
#'   \item{abstract_inverted_index.Republic}{}
#'   \item{abstract_inverted_index.region}{}
#'   \item{abstract_inverted_index.faces}{}
#'   \item{abstract_inverted_index.due}{}
#'   \item{abstract_inverted_index4,}{}
#'   \item{abstract_inverted_index.increasingly}{}
#'   \item{abstract_inverted_index.challenging}{}
#'   \item{abstract_inverted_index.recent}{}
#'   \item{abstract_inverted_index.attributed}{}
#'   \item{abstract_inverted_index.range}{}
#'   \item{abstract_inverted_index.building}{}
#'   \item{abstract_inverted_index.studied}{}
#'   \item{abstract_inverted_index.February}{}
#'   \item{abstract_inverted_index.biological}{}
#'   \item{abstract_inverted_index.parameters}{}
#'   \item{abstract_inverted_index.pH,}{}
#'   \item{abstract_inverted_index.total}{}
#'   \item{abstract_inverted_index.count}{}
#'   \item{abstract_inverted_index.analyzed}{}
#'   \item{abstract_inverted_index.understand}{}
#'   \item{abstract_inverted_index.differences}{}
#'   \item{abstract_inverted_index.within}{}
#'   \item{abstract_inverted_index.chlorine}{}
#'   \item{abstract_inverted_index.concentration}{}
#'   \item{abstract_inverted_index.decreased}{}
#'   \item{abstract_inverted_index.(}{}
#'   \item{abstract_inverted_index.p}{}
#'   \item{abstract_inverted_index.&lt;}{}
#'   \item{abstract_inverted_index.point}{}
#'   \item{abstract_inverted_index.plumbing}{}
#'   \item{abstract_inverted_index.As}{}
#'   \item{abstract_inverted_index.much}{}
#'   \item{abstract_inverted_index.greater}{}
#'   \item{abstract_inverted_index.compared}{}
#'   \item{abstract_inverted_index.every}{}
#'   \item{abstract_inverted_index.sampling}{}
#'   \item{abstract_inverted_index.found}{}
#'   \item{abstract_inverted_index.highest}{}
#'   \item{abstract_inverted_index.no}{}
#'   \item{abstract_inverted_index.recorded}{}
#'   \item{abstract_inverted_index.during}{}
#'   \item{abstract_inverted_index.lead}{}
#'   \item{abstract_inverted_index.health-based}{}
#'   \item{abstract_inverted_index.drinking}{}
#'   \item{abstract_inverted_index.four}{}
#'   \item{abstract_inverted_index.same}{}
#'   \item{abstract_inverted_index.shared}{}
#'   \item{abstract_inverted_index.use.}{}
#'   \item{abstract_inverted_index.conducted}{}
#'   \item{abstract_inverted_index.one}{}
#'   \item{abstract_inverted_index.required}{}
#'   \item{abstract_inverted_index.supply.}{}
#'   \item{abstract_inverted_index.viable}{}
#'   \item{abstract_inverted_index.method}{}
#'   \item{abstract_inverted_index.need}{}
#'   \item{abstract_inverted_index.19}{}
#'   \item{abstract_inverted_index.than}{}
#'   \item{abstract_inverted_index.50}{}
#'   \item{abstract_inverted_index.before}{}
#'   \item{abstract_inverted_index.prior}{}
#'   \item{abstract_inverted_index.suggest}{}
#'   \item{abstract_inverted_index.significantly}{}
#'   \item{abstract_inverted_index.implications}{}
#'   \item{abstract_inverted_index.collected}{}
#'   \item{abstract_inverted_index.infrastructure}{}
#'   \item{abstract_inverted_index.engineering}{}
#'   \item{abstract_inverted_index.security}{}
#'   \item{abstract_inverted_index.In}{}
#'   \item{abstract_inverted_index.freshwater}{}
#'   \item{abstract_inverted_index.society}{}
#'   \item{abstract_inverted_index.environment}{}
#'   \item{abstract_inverted_index.could}{}
#'   \item{abstract_inverted_index.benefit}{}
#'   \item{abstract_inverted_index.Such}{}
#'   \item{abstract_inverted_index.conservation}{}
#'   \item{abstract_inverted_index.ongoing}{}
#'   \item{abstract_inverted_index.species}{}
#'   \item{abstract_inverted_index.their}{}
#'   \item{abstract_inverted_index.systems.}{}
#'   \item{abstract_inverted_index.However,}{}
#'   \item{abstract_inverted_index.make}{}
#'   \item{abstract_inverted_index.meaningful}{}
#'   \item{abstract_inverted_index.contributions}{}
#'   \item{abstract_inverted_index.must}{}
#'   \item{abstract_inverted_index.established}{}
#'   \item{abstract_inverted_index.link}{}
#'   \item{abstract_inverted_index.common}{}
#'   \item{abstract_inverted_index.six}{}
#'   \item{abstract_inverted_index.actions}{}
#'   \item{abstract_inverted_index.life}{}
#'   \item{abstract_inverted_index.science}{}
#'   \item{abstract_inverted_index.highlight}{}
#'   \item{abstract_inverted_index.knowledge}{}
#'   \item{abstract_inverted_index.necessary}{}
#'   \item{abstract_inverted_index.how}{}
#'   \item{abstract_inverted_index.play}{}
#'   \item{abstract_inverted_index.direct}{}
#'   \item{abstract_inverted_index.aquatic}{}
#'   \item{abstract_inverted_index.quality,}{}
#'   \item{abstract_inverted_index.ecosystems.}{}
#'   \item{abstract_inverted_index.ensure}{}
#'   \item{abstract_inverted_index.ecosystems}{}
#'   \item{abstract_inverted_index.species.}{}
#'   \item{abstract_inverted_index.Water}{}
#'   \item{abstract_inverted_index.managers}{}
#'   \item{abstract_inverted_index.consider}{}
#'   \item{abstract_inverted_index.whether}{}
#'   \item{abstract_inverted_index.concern}{}
#'   \item{abstract_inverted_index.reservoir}{}
#'   \item{abstract_inverted_index.management,}{}
#'   \item{abstract_inverted_index.modeling}{}
#'   \item{abstract_inverted_index.requires}{}
#'   \item{abstract_inverted_index.models}{}
#'   \item{abstract_inverted_index.watershed}{}
#'   \item{abstract_inverted_index.various}{}
#'   \item{abstract_inverted_index.most}{}
#'   \item{abstract_inverted_index.practical}{}
#'   \item{abstract_inverted_index.selecting}{}
#'   \item{abstract_inverted_index.availability}{}
#'   \item{abstract_inverted_index.number}{}
#'   \item{abstract_inverted_index.decisions}{}
#'   \item{abstract_inverted_index.regarding}{}
#'   \item{abstract_inverted_index.best}{}
#'   \item{abstract_inverted_index.relative}{}
#'   \item{abstract_inverted_index.importance}{}
#'   \item{abstract_inverted_index.different}{}
#'   \item{abstract_inverted_index.limited}{}
#'   \item{abstract_inverted_index.should}{}
#'   \item{abstract_inverted_index.assess}{}
#'   \item{abstract_inverted_index.existing}{}
#'   \item{abstract_inverted_index.then}{}
#'   \item{abstract_inverted_index.limitations}{}
#'   \item{abstract_inverted_index.questions}{}
#'   \item{abstract_inverted_index.previous}{}
#'   \item{abstract_inverted_index.While}{}
#'   \item{abstract_inverted_index.there}{}
#'   \item{abstract_inverted_index.work}{}
#'   \item{abstract_inverted_index.options}{}
#'   \item{abstract_inverted_index.activity}{}
#'   \item{abstract_inverted_index.leading}{}
#'   \item{abstract_inverted_index.widespread}{}
#'   \item{abstract_inverted_index.lake}{}
#'   \item{abstract_inverted_index.key}{}
#'   \item{abstract_inverted_index.health.}{}
#'   \item{abstract_inverted_index.anthropogenic}{}
#'   \item{abstract_inverted_index.affecting}{}
#'   \item{abstract_inverted_index.space}{}
#'   \item{abstract_inverted_index.potentially}{}
#'   \item{abstract_inverted_index.highly}{}
#'   \item{abstract_inverted_index.responses}{}
#'   \item{abstract_inverted_index.poorly}{}
#'   \item{abstract_inverted_index.million}{}
#'   \item{abstract_inverted_index.estimates}{}
#'   \item{abstract_inverted_index.4}{}
#'   \item{abstract_inverted_index.km}{}
#'   \item{abstract_inverted_index.quantify}{}
#'   \item{abstract_inverted_index.2020}{}
#'   \item{abstract_inverted_index.large}{}
#'   \item{abstract_inverted_index.cumulative}{}
#'   \item{abstract_inverted_index.increase}{}
#'   \item{abstract_inverted_index.human}{}
#'   \item{abstract_inverted_index.lakes}{}
#'   \item{abstract_inverted_index.positive}{}
#'   \item{abstract_inverted_index.trends}{}
#'   \item{abstract_inverted_index.times}{}
#'   \item{abstract_inverted_index.demonstrates}{}
#'   \item{abstract_inverted_index.inform}{}
#'   \item{abstract_inverted_index.management}{}
#'   \item{abstract_inverted_index.determine}{}
#'   \item{abstract_inverted_index.local}{}
#'   \item{abstract_inverted_index.Existing}{}
#'   \item{abstract_inverted_index.literature}{}
#'   \item{abstract_inverted_index.water,}{}
#'   \item{abstract_inverted_index.sanitation,}{}
#'   \item{abstract_inverted_index.hygiene}{}
#'   \item{abstract_inverted_index.(WASH)}{}
#'   \item{abstract_inverted_index.United}{}
#'   \item{abstract_inverted_index.States,}{}
#'   \item{abstract_inverted_index.issues}{}
#'   \item{abstract_inverted_index.areas.}{}
#'   \item{abstract_inverted_index.emerging}{}
#'   \item{abstract_inverted_index.infectious}{}
#'   \item{abstract_inverted_index.disease}{}
#'   \item{abstract_inverted_index.face}{}
#'   \item{abstract_inverted_index.challenges}{}
#'   \item{abstract_inverted_index.urban}{}
#'   \item{abstract_inverted_index.study}{}
#'   \item{abstract_inverted_index.WASH}{}
#'   \item{abstract_inverted_index.needs}{}
#'   \item{abstract_inverted_index.through}{}
#'   \item{abstract_inverted_index.interviews}{}
#'   \item{abstract_inverted_index.(n}{}
#'   \item{abstract_inverted_index.=}{}
#'   \item{abstract_inverted_index.participants}{}
#'   \item{abstract_inverted_index.18}{}
#'   \item{abstract_inverted_index.years}{}
#'   \item{abstract_inverted_index.lived}{}
#'   \item{abstract_inverted_index.five}{}
#'   \item{abstract_inverted_index.had}{}
#'   \item{abstract_inverted_index.Using}{}
#'   \item{abstract_inverted_index.analysis,}{}
#'   \item{abstract_inverted_index.factors}{}
#'   \item{abstract_inverted_index.access,}{}
#'   \item{abstract_inverted_index.outcomes}{}
#'   \item{abstract_inverted_index.result}{}
#'   \item{abstract_inverted_index.explore}{}
#'   \item{abstract_inverted_index.experiences}{}
#'   \item{abstract_inverted_index.who}{}
#'   \item{abstract_inverted_index.those}{}
#'   \item{abstract_inverted_index.did}{}
#'   \item{abstract_inverted_index.not.}{}
#'   \item{abstract_inverted_index.Our}{}
#'   \item{abstract_inverted_index.findings}{}
#'   \item{abstract_inverted_index.revealed}{}
#'   \item{abstract_inverted_index.contributed}{}
#'   \item{abstract_inverted_index.physical,}{}
#'   \item{abstract_inverted_index.relationship}{}
#'   \item{abstract_inverted_index.communities}{}
#'   \item{abstract_inverted_index.impacted}{}
#'   \item{abstract_inverted_index.facilities}{}
#'   \item{abstract_inverted_index.safe}{}
#'   \item{abstract_inverted_index.available}{}
#'   \item{abstract_inverted_index.inadequate}{}
#'   \item{abstract_inverted_index.access}{}
#'   \item{abstract_inverted_index.collaboration}{}
#'   \item{abstract_inverted_index.reduction}{}
#'   \item{abstract_inverted_index.services}{}
#'   \item{abstract_inverted_index.example,}{}
#'   \item{abstract_inverted_index.hand}{}
#'   \item{abstract_inverted_index.community}{}
#'   \item{abstract_inverted_index.measures}{}
#'   \item{abstract_inverted_index.transmission}{}
#'   \item{abstract_inverted_index.COVID-19}{}
#'   \item{abstract_inverted_index.other}{}
#'   \item{abstract_inverted_index.diseases.}{}
#'   \item{abstract_inverted_index.guidance}{}
#'   \item{abstract_inverted_index.standards}{}
#'   \item{abstract_inverted_index.new}{}
#'   \item{abstract_inverted_index.tools}{}
#'   \item{abstract_inverted_index.targeted}{}
#'   \item{abstract_inverted_index.assessments}{}
#'   \item{abstract_inverted_index.pandemic.}{}
#'   \item{abstract_inverted_index.organizations}{}
#'   \item{abstract_inverted_index.evaluate}{}
#'   \item{abstract_inverted_index.interventions}{}
#'   \item{abstract_inverted_index.mitigate}{}
#'   \item{abstract_inverted_index.middle-income}{}
#'   \item{abstract_inverted_index.countries}{}
#'   \item{abstract_inverted_index.focusing}{}
#'   \item{abstract_inverted_index.household}{}
#'   \item{abstract_inverted_index.settings}{}
#'   \item{abstract_inverted_index.observed}{}
#'   \item{abstract_inverted_index.gaps}{}
#'   \item{abstract_inverted_index.specifically}{}
#'   \item{abstract_inverted_index.often}{}
#'   \item{abstract_inverted_index.about}{}
#'   \item{abstract_inverted_index.high}{}
#'   \item{abstract_inverted_index.after}{}
#'   \item{abstract_inverted_index.stations}{}
#'   \item{abstract_inverted_index.points}{}
#'   \item{abstract_inverted_index.external}{}
#'   \item{abstract_inverted_index.needed.}{}
#'   \item{abstract_inverted_index.refinement}{}
#'   \item{abstract_inverted_index.help}{}
#'   \item{abstract_inverted_index.aspects}{}
#'   \item{abstract_inverted_index.efforts}{}
#'   \item{abstract_inverted_index.remain}{}
#'   \item{abstract_inverted_index.functional}{}
#'   \item{abstract_inverted_index.inclusive}{}
#'   \item{abstract_inverted_index.U.S.}{}
#'   \item{abstract_inverted_index.service}{}
#'   \item{abstract_inverted_index.health,}{}
#'   \item{abstract_inverted_index.economic}{}
#'   \item{abstract_inverted_index.expressed}{}
#'   \item{abstract_inverted_index.sample}{}
#'   \item{abstract_inverted_index.approximately}{}
#'   \item{abstract_inverted_index.city}{}
#'   \item{abstract_inverted_index.perceptions}{}
#'   \item{abstract_inverted_index.barriers}{}
#'   \item{abstract_inverted_index.meeting}{}
#'   \item{abstract_inverted_index.question}{}
#'   \item{abstract_inverted_index.cost}{}
#'   \item{abstract_inverted_index.capital}{}
#'   \item{abstract_inverted_index.projects}{}
#'   \item{abstract_inverted_index.increases}{}
#'   \item{abstract_inverted_index.infrastructure.}{}
#'   \item{abstract_inverted_index.demonstrate}{}
#'   \item{abstract_inverted_index.disparities}{}
#'   \item{abstract_inverted_index.great}{}
#'   \item{abstract_inverted_index.little}{}
#'   \item{abstract_inverted_index.condition}{}
#'   \item{abstract_inverted_index.making}{}
#'   \item{abstract_inverted_index.financial}{}
#'   \item{abstract_inverted_index.decision}{}
#'   \item{abstract_inverted_index.clean}{}
#'   \item{abstract_inverted_index.substantial}{}
#'   \item{abstract_inverted_index.States}{}
#'   \item{abstract_inverted_index.cannot}{}
#'   \item{abstract_inverted_index.pathways}{}
#'   \item{abstract_inverted_index.influence}{}
#'   \item{abstract_inverted_index.behaviors}{}
#'   \item{abstract_inverted_index.vulnerable}{}
#'   \item{abstract_inverted_index.interviewed}{}
#'   \item{abstract_inverted_index.low-income}{}
#'   \item{abstract_inverted_index.bill}{}
#'   \item{abstract_inverted_index.content}{}
#'   \item{abstract_inverted_index.interview}{}
#'   \item{abstract_inverted_index.Results}{}
#'   \item{abstract_inverted_index.showed}{}
#'   \item{abstract_inverted_index.ways}{}
#'   \item{abstract_inverted_index.made}{}
#'   \item{abstract_inverted_index.times.}{}
#'   \item{abstract_inverted_index.influenced}{}
#'   \item{abstract_inverted_index.utility}{}
#'   \item{abstract_inverted_index.included}{}
#'   \item{abstract_inverted_index.reduced}{}
#'   \item{abstract_inverted_index.decline}{}
#'   \item{abstract_inverted_index.government}{}
#'   \item{abstract_inverted_index.affordable}{}
#'   \item{abstract_inverted_index.households.}{}
#'   \item{abstract_inverted_index.infrastructure,}{}
#'   \item{abstract_inverted_index.state}{}
#'   \item{abstract_inverted_index.well}{}
#'   \item{abstract_inverted_index.municipal}{}
#'   \item{abstract_inverted_index.policies}{}
#'   \item{abstract_inverted_index.households}{}
#'   \item{abstract_inverted_index.growing}{}
#'   \item{abstract_inverted_index.residents}{}
#'   \item{abstract_inverted_index.balance}{}
#'   \item{abstract_inverted_index.resulting}{}
#'   \item{abstract_inverted_index.affect}{}
#'   \item{abstract_inverted_index.loss}{}
#'   \item{abstract_inverted_index.impact}{}
#'   \item{abstract_inverted_index.system,}{}
#'   \item{abstract_inverted_index.influencing}{}
#'   \item{abstract_inverted_index.frequency}{}
#'   \item{abstract_inverted_index.During}{}
#'   \item{abstract_inverted_index.past}{}
#'   \item{abstract_inverted_index.basin}{}
#'   \item{abstract_inverted_index.uses}{}
#'   \item{abstract_inverted_index.along}{}
#'   \item{abstract_inverted_index.predicted}{}
#'   \item{abstract_inverted_index.temporal}{}
#'   \item{abstract_inverted_index.spatial}{}
#'   \item{abstract_inverted_index.sediment}{}
#'   \item{abstract_inverted_index.effective}{}
#'   \item{abstract_inverted_index.50%}{}
#'   \item{abstract_inverted_index.baseline}{}
#'   \item{abstract_inverted_index.cause}{}
#'   \item{abstract_inverted_index.3%}{}
#'   \item{abstract_inverted_index.mean}{}
#'   \item{abstract_inverted_index.surface}{}
#'   \item{abstract_inverted_index.solid}{}
#'   \item{abstract_inverted_index.estimated}{}
#'   \item{abstract_inverted_index.concentrations}{}
#'   \item{abstract_inverted_index.cover}{}
#'   \item{abstract_inverted_index.biochar}{}
#'   \item{abstract_inverted_index.remove}{}
#'   \item{abstract_inverted_index.improve}{}
#'   \item{abstract_inverted_index.P}{}
#'   \item{abstract_inverted_index.molecular}{}
#'   \item{abstract_inverted_index.carbon}{}
#'   \item{abstract_inverted_index.produced}{}
#'   \item{abstract_inverted_index.under}{}
#'   \item{abstract_inverted_index.3}{}
#'   \item{abstract_inverted_index.gas}{}
#'   \item{abstract_inverted_index.mass}{}
#'   \item{abstract_inverted_index.capacities}{}
#'   \item{abstract_inverted_index.near}{}
#'   \item{abstract_inverted_index.structure}{}
#'   \item{abstract_inverted_index.indicated}{}
#'   \item{abstract_inverted_index.advance}{}
#'   \item{abstract_inverted_index.treatment}{}
#'   \item{abstract_inverted_index.processes}{}
#'   \item{abstract_inverted_index.employed}{}
#'   \item{abstract_inverted_index.stormwater}{}
#'   \item{abstract_inverted_index.stream}{}
#'   \item{abstract_inverted_index.performance}{}
#'   \item{abstract_inverted_index.metrics}{}
#'   \item{abstract_inverted_index.they}{}
#'   \item{abstract_inverted_index.catchment}{}
#'   \item{abstract_inverted_index.aimed}{}
#'   \item{abstract_inverted_index.response}{}
#'   \item{abstract_inverted_index.application}{}
#'   \item{abstract_inverted_index.experiment}{}
#'   \item{abstract_inverted_index.test}{}
#'   \item{abstract_inverted_index.improved}{}
#'   \item{abstract_inverted_index.achieved}{}
#'   \item{abstract_inverted_index.experimental}{}
#'   \item{abstract_inverted_index.similar}{}
#'   \item{abstract_inverted_index.per}{}
#'   \item{abstract_inverted_index.implementation}{}
#'   \item{abstract_inverted_index.achieve}{}
#'   \item{abstract_inverted_index.success}{}
#'   \item{abstract_inverted_index.final}{}
#'   \item{abstract_inverted_index.into}{}
#'   \item{abstract_inverted_index.demand}{}
#'   \item{abstract_inverted_index.measure}{}
#'   \item{abstract_inverted_index.period}{}
#'   \item{abstract_inverted_index.varied}{}
#'   \item{abstract_inverted_index.modelling}{}
#'   \item{abstract_inverted_index.broader}{}
#'   \item{abstract_inverted_index.decades}{}
#'   \item{abstract_inverted_index.environmental}{}
#'   \item{abstract_inverted_index.surveillance}{}
#'   \item{abstract_inverted_index.pathogens}{}
#'   \item{abstract_inverted_index.single}{}
#'   \item{abstract_inverted_index.pathogen}{}
#'   \item{abstract_inverted_index.small}{}
#'   \item{abstract_inverted_index.few}{}
#'   \item{abstract_inverted_index.quantitative}{}
#'   \item{abstract_inverted_index.developed}{}
#'   \item{abstract_inverted_index.targets}{}
#'   \item{abstract_inverted_index.applied}{}
#'   \item{abstract_inverted_index.samples}{}
#'   \item{abstract_inverted_index.plants}{}
#'   \item{abstract_inverted_index.From}{}
#'   \item{abstract_inverted_index.detected}{}
#'   \item{abstract_inverted_index.find}{}
#'   \item{abstract_inverted_index.E}{}
#'   \item{abstract_inverted_index..}{}
#'   \item{abstract_inverted_index.coli}{}
#'   \item{abstract_inverted_index.stable}{}
#'   \item{abstract_inverted_index.notable}{}
#'   \item{abstract_inverted_index.,}{}
#'   \item{abstract_inverted_index.broad}{}
#'   \item{abstract_inverted_index.expanding}{}
#'   \item{abstract_inverted_index.fecal}{}
#'   \item{abstract_inverted_index.waste}{}
#'   \item{abstract_inverted_index.solids}{}
#'   \item{abstract_inverted_index.changed}{}
#'   \item{abstract_inverted_index.objective}{}
#'   \item{abstract_inverted_index.One}{}
#'   \item{abstract_inverted_index.when}{}
#'   \item{abstract_inverted_index.To}{}
#'   \item{abstract_inverted_index.trend}{}
#'   \item{abstract_inverted_index.index}{}
#'   \item{abstract_inverted_index.measurements}{}
#'   \item{abstract_inverted_index.characterize}{}
#'   \item{abstract_inverted_index.trends.}{}
#'   \item{abstract_inverted_index.better}{}
#'   \item{abstract_inverted_index.so}{}
#'   \item{abstract_inverted_index.5}{}
#'   \item{abstract_inverted_index.detect}{}
#'   \item{abstract_inverted_index.respectively.}{}
#'   \item{abstract_inverted_index.providing}{}
#'   \item{abstract_inverted_index.changing}{}
#'   \item{abstract_inverted_index.2021}{}
#'   \item{abstract_inverted_index.without}{}
#'   \item{abstract_inverted_index.domestic}{}
#'   \item{abstract_inverted_index.systems}{}
#'   \item{abstract_inverted_index.performed}{}
#'   \item{abstract_inverted_index.combined}{}
#'   \item{abstract_inverted_index.Texas}{}
#'   \item{abstract_inverted_index.affected}{}
#'   \item{abstract_inverted_index.populations}{}
#'   \item{abstract_inverted_index.cross-sectional}{}
#'   \item{abstract_inverted_index.survey}{}
#'   \item{abstract_inverted_index.shows}{}
#'   \item{abstract_inverted_index.size}{}
#'   \item{abstract_inverted_index.system.}{}
#'   \item{abstract_inverted_index.mostly}{}
#'   \item{abstract_inverted_index.disproportionately}{}
#'   \item{abstract_inverted_index.likely}{}
#'   \item{abstract_inverted_index.utilities}{}
#'   \item{abstract_inverted_index.respondents}{}
#'   \item{abstract_inverted_index.resilience}{}
#'   \item{abstract_inverted_index.efficient}{}
#'   \item{abstract_inverted_index.emergency}{}
#'   \item{abstract_inverted_index.physical}{}
#'   \item{abstract_inverted_index.based}{}
#'   \item{abstract_inverted_index.system}{}
#'   \item{abstract_inverted_index.complex}{}
#'   \item{abstract_inverted_index.conventional}{}
#'   \item{abstract_inverted_index.remote}{}
#'   \item{abstract_inverted_index.sensing}{}
#'   \item{abstract_inverted_index.New}{}
#'   \item{abstract_inverted_index.addressing}{}
#'   \item{abstract_inverted_index.mainly}{}
#'   \item{abstract_inverted_index.types}{}
#'   \item{abstract_inverted_index.problems}{}
#'   \item{abstract_inverted_index.challenges,}{}
#'   \item{abstract_inverted_index.identify}{}
#'   \item{abstract_inverted_index.opportunities}{}
#'   \item{abstract_inverted_index.hydrology}{}
#'   \item{abstract_inverted_index.around}{}
#'   \item{abstract_inverted_index.insights}{}
#'   \item{abstract_inverted_index.just}{}
#'   \item{abstract_inverted_index.propose}{}
#'   \item{abstract_inverted_index.larger}{}
#'   \item{abstract_inverted_index.big}{}
#'   \item{abstract_inverted_index.call}{}
#'   \item{abstract_inverted_index.action}{}
#'   \item{abstract_inverted_index.context}{}
#'   \item{abstract_inverted_index.practice}{}
#'   \item{abstract_inverted_index.sector}{}
#'   \item{abstract_inverted_index.private}{}
#'   \item{abstract_inverted_index.engagement}{}
#'   \item{abstract_inverted_index.good}{}
#'   \item{abstract_inverted_index.very}{}
#'   \item{abstract_inverted_index.issue}{}
#'   \item{abstract_inverted_index.pollution}{}
#'   \item{abstract_inverted_index.throughout}{}
#'   \item{abstract_inverted_index.entire}{}
#'   \item{abstract_inverted_index.West}{}
#'   \item{abstract_inverted_index.distribution}{}
#'   \item{abstract_inverted_index.pollutants}{}
#'   \item{abstract_inverted_index.considering}{}
#'   \item{abstract_inverted_index.level,}{}
#'   \item{abstract_inverted_index.next}{}
#'   \item{abstract_inverted_index.generated}{}
#'   \item{abstract_inverted_index.level}{}
#'   \item{abstract_inverted_index.each}{}
#'   \item{abstract_inverted_index.selected}{}
#'   \item{abstract_inverted_index.estimate}{}
#'   \item{abstract_inverted_index.low}{}
#'   \item{abstract_inverted_index.alternative}{}
#'   \item{abstract_inverted_index.solution}{}
#'   \item{abstract_inverted_index.globally}{}
#'   \item{abstract_inverted_index.precipitation,}{}
#'   \item{abstract_inverted_index.processes.}{}
#'   \item{abstract_inverted_index.performance.}{}
#'   \item{abstract_inverted_index.estimating}{}
#'   \item{abstract_inverted_index.characteristics}{}
#'   \item{abstract_inverted_index.remains}{}
#'   \item{abstract_inverted_index.models,}{}
#'   \item{abstract_inverted_index.method.}{}
#'   \item{abstract_inverted_index.Spatial}{}
#'   \item{abstract_inverted_index.associated}{}
#'   \item{abstract_inverted_index.cold}{}
#'   \item{abstract_inverted_index.association}{}
#'   \item{abstract_inverted_index.variations}{}
#'   \item{abstract_inverted_index.operational}{}
#'   \item{abstract_inverted_index.full-scale}{}
#'   \item{abstract_inverted_index.integration}{}
#'   \item{abstract_inverted_index.chemical}{}
#'   \item{abstract_inverted_index.accumulation}{}
#'   \item{abstract_inverted_index.being}{}
#'   \item{abstract_inverted_index.driver}{}
#'   \item{abstract_inverted_index.upon}{}
#'   \item{abstract_inverted_index.complex,}{}
#'   \item{abstract_inverted_index.indicating}{}
#'   \item{abstract_inverted_index.These}{}
#'   \item{abstract_inverted_index.water.}{}
#'   \item{abstract_inverted_index.By}{}
#'   \item{abstract_inverted_index.process,}{}
#'   \item{abstract_inverted_index.targeting}{}
#'   \item{abstract_inverted_index.long-term}{}
#'   \item{abstract_inverted_index.quality.}{}
#'   \item{abstract_inverted_index.urbanization,}{}
#'   \item{abstract_inverted_index.population}{}
#'   \item{abstract_inverted_index.inequality}{}
#'   \item{abstract_inverted_index.study,}{}
#'   \item{abstract_inverted_index.peri-urban}{}
#'   \item{abstract_inverted_index.examine}{}
#'   \item{abstract_inverted_index.explained}{}
#'   \item{abstract_inverted_index.regression}{}
#'   \item{abstract_inverted_index.source}{}
#'   \item{abstract_inverted_index.pressure}{}
#'   \item{abstract_inverted_index.supply}{}
#'   \item{abstract_inverted_index.odds}{}
#'   \item{abstract_inverted_index.ratio}{}
#'   \item{abstract_inverted_index.factor}{}
#'   \item{abstract_inverted_index.Findings}{}
#'   \item{abstract_inverted_index.even}{}
#'   \item{abstract_inverted_index.services,}{}
#'   \item{abstract_inverted_index.stakeholders}{}
#'   \item{abstract_inverted_index.guide}{}
#'   \item{abstract_inverted_index.infrastructural}{}
#'   \item{abstract_inverted_index.settings.}{}
#'   \item{abstract_inverted_index.dynamics}{}
#'   \item{abstract_inverted_index.transboundary}{}
#'   \item{abstract_inverted_index.nature}{}
#'   \item{abstract_inverted_index.cross}{}
#'   \item{abstract_inverted_index.rivers,}{}
#'   \item{abstract_inverted_index.Thus,}{}
#'   \item{abstract_inverted_index.defined}{}
#'   \item{abstract_inverted_index.beyond}{}
#'   \item{abstract_inverted_index.field}{}
#'   \item{abstract_inverted_index.concept.}{}
#'   \item{abstract_inverted_index.With}{}
#'   \item{abstract_inverted_index.riverine}{}
#'   \item{abstract_inverted_index.become}{}
#'   \item{abstract_inverted_index.crucial}{}
#'   \item{abstract_inverted_index.study.}{}
#'   \item{abstract_inverted_index.i.e.,}{}
#'   \item{abstract_inverted_index.Yet,}{}
#'   \item{abstract_inverted_index.primary}{}
#'   \item{abstract_inverted_index.because}{}
#'   \item{abstract_inverted_index.cities}{}
#'   \item{abstract_inverted_index.Moreover,}{}
#'   \item{abstract_inverted_index.what}{}
#'   \item{abstract_inverted_index.them}{}
#'   \item{abstract_inverted_index.do}{}
#'   \item{abstract_inverted_index.ability}{}
#'   \item{abstract_inverted_index.extensive}{}
#'   \item{abstract_inverted_index.qualitative}{}
#'   \item{abstract_inverted_index.South}{}
#'   \item{abstract_inverted_index.purpose}{}
#'   \item{abstract_inverted_index.article}{}
#'   \item{abstract_inverted_index.poor}{}
#'   \item{abstract_inverted_index.toward}{}
#'   \item{abstract_inverted_index.community.}{}
#'   \item{abstract_inverted_index.include}{}
#'   \item{abstract_inverted_index.education}{}
#'   \item{abstract_inverted_index.towards}{}
#'   \item{abstract_inverted_index.equitable}{}
#'   \item{abstract_inverted_index.and,}{}
#'   \item{abstract_inverted_index.on-site}{}
#'   \item{abstract_inverted_index.aims}{}
#'   \item{abstract_inverted_index.taken}{}
#'   \item{abstract_inverted_index.parameters.}{}
#'   \item{abstract_inverted_index.hydrologic}{}
#'   \item{abstract_inverted_index.while}{}
#'   \item{abstract_inverted_index.assessed}{}
#'   \item{abstract_inverted_index.downstream}{}
#'   \item{abstract_inverted_index.difficulties}{}
#'   \item{abstract_inverted_index.simulate}{}
#'   \item{abstract_inverted_index.conditions,}{}
#'   \item{abstract_inverted_index.contaminants.}{}
#'   \item{abstract_inverted_index.scale}{}
#'   \item{abstract_inverted_index.National}{}
#'   \item{abstract_inverted_index.Monitoring}{}
#'   \item{abstract_inverted_index.monitored}{}
#'   \item{abstract_inverted_index.antimicrobial}{}
#'   \item{abstract_inverted_index.alignment}{}
#'   \item{abstract_inverted_index.Health}{}
#'   \item{abstract_inverted_index.planning,}{}
#'   \item{abstract_inverted_index.waters}{}
#'   \item{abstract_inverted_index.function}{}
#'   \item{abstract_inverted_index.humans,}{}
#'   \item{abstract_inverted_index.animals,}{}
#'   \item{abstract_inverted_index.environment.}{}
#'   \item{abstract_inverted_index.sequencing}{}
#'   \item{abstract_inverted_index.coverage}{}
#'   \item{abstract_inverted_index.shown}{}
#'   \item{abstract_inverted_index.enhance}{}
#'   \item{abstract_inverted_index.report}{}
#'   \item{abstract_inverted_index.profile}{}
#'   \item{abstract_inverted_index.distinct}{}
#'   \item{abstract_inverted_index.sites}{}
#'   \item{abstract_inverted_index.enriched}{}
#'   \item{abstract_inverted_index.almost}{}
#'   \item{abstract_inverted_index.30%}{}
#'   \item{abstract_inverted_index.Additionally,}{}
#'   \item{abstract_inverted_index.specific}{}
#'   \item{abstract_inverted_index.sites.}{}
#'   \item{abstract_inverted_index.Development}{}
#'   \item{abstract_inverted_index.technologies}{}
#'   \item{abstract_inverted_index.vulnerability}{}
#'   \item{abstract_inverted_index.scheme}{}
#'   \item{abstract_inverted_index.design}{}
#'   \item{abstract_inverted_index.period.}{}
#'   \item{abstract_inverted_index.variables}{}
#'   \item{abstract_inverted_index.less}{}
#'   \item{abstract_inverted_index.treatment.}{}
#'   \item{abstract_inverted_index.conclude}{}
#'   \item{abstract_inverted_index.appropriate}{}
#'   \item{abstract_inverted_index.urgent}{}
#'   \item{abstract_inverted_index.set}{}
#'   \item{abstract_inverted_index.pressures}{}
#'   \item{abstract_inverted_index.wastewater,}{}
#'   \item{abstract_inverted_index.maintain}{}
#'   \item{abstract_inverted_index.involve}{}
#'   \item{abstract_inverted_index.general}{}
#'   \item{abstract_inverted_index.way}{}
#'   \item{abstract_inverted_index.get}{}
#'   \item{abstract_inverted_index.participation}{}
#'   \item{abstract_inverted_index.world}{}
#'   \item{abstract_inverted_index.take}{}
#'   \item{abstract_inverted_index.groundwater}{}
#'   \item{abstract_inverted_index.science,}{}
#'   \item{abstract_inverted_index.respect}{}
#'   \item{abstract_inverted_index.authorities}{}
#'   \item{abstract_inverted_index.social}{}
#'   \item{abstract_inverted_index.knowledge,}{}
#'   \item{abstract_inverted_index.environment,}{}
#'   \item{abstract_inverted_index.encourage}{}
#'   \item{abstract_inverted_index.tap}{}
#'   \item{abstract_inverted_index.effect}{}
#'   \item{abstract_inverted_index.composition}{}
#'   \item{abstract_inverted_index.relatively}{}
#'   \item{abstract_inverted_index.simple}{}
#'   \item{abstract_inverted_index.adapted}{}
#'   \item{abstract_inverted_index.expertise}{}
#'   \item{abstract_inverted_index.manage}{}
#'   \item{abstract_inverted_index.safety}{}
#'   \item{abstract_inverted_index.exacerbated}{}
#'   \item{abstract_inverted_index.working}{}
#'   \item{abstract_inverted_index.capacity,}{}
#'   \item{abstract_inverted_index.informant}{}
#'   \item{abstract_inverted_index.10}{}
#'   \item{abstract_inverted_index.risks}{}
#'   \item{abstract_inverted_index.led}{}
#'   \item{abstract_inverted_index.adequate}{}
#'   \item{abstract_inverted_index.diseases}{}
#'   \item{abstract_inverted_index.investigated}{}
#'   \item{abstract_inverted_index.recommended}{}
#'   \item{abstract_inverted_index.active}{}
#'   \item{abstract_inverted_index.training}{}
#'   \item{abstract_inverted_index.flood}{}
#'   \item{abstract_inverted_index.treated}{}
#'   \item{abstract_inverted_index.industrial}{}
#'   \item{abstract_inverted_index.demands}{}
#'   \item{abstract_inverted_index.up}{}
#'   \item{abstract_inverted_index.put}{}
#'   \item{abstract_inverted_index.governance}{}
#'   \item{abstract_inverted_index.respond}{}
#'   \item{abstract_inverted_index.values}{}
#'   \item{abstract_inverted_index.complexities}{}
#'   \item{abstract_inverted_index.status}{}
#'   \item{abstract_inverted_index.time,}{}
#'   \item{abstract_inverted_index.exist}{}
#'   \item{abstract_inverted_index.groups}{}
#'   \item{abstract_inverted_index.regional}{}
#'   \item{abstract_inverted_index.networks}{}
#'   \item{abstract_inverted_index.representation}{}
#'   \item{abstract_inverted_index.operate}{}
#'   \item{abstract_inverted_index.activities}{}
#'   \item{abstract_inverted_index.project}{}
#'   \item{abstract_inverted_index.designs}{}
#'   \item{abstract_inverted_index.largest}{}
#'   \item{abstract_inverted_index.located}{}
#'   \item{abstract_inverted_index.m}{}
#'   \item{abstract_inverted_index.meet}{}
#'   \item{abstract_inverted_index.income}{}
#'   \item{abstract_inverted_index.census}{}
#'   \item{abstract_inverted_index.users}{}
#'   \item{abstract_inverted_index.).}{}
#'   \item{abstract_inverted_index.rather}{}
#'   \item{abstract_inverted_index.patterns,}{}
#'   \item{abstract_inverted_index.patterns}{}
#'   \item{abstract_inverted_index.products}{}
#'   \item{abstract_inverted_index.techniques}{}
#'   \item{abstract_inverted_index.addition}{}
#'   \item{abstract_inverted_index.evaluated}{}
#'   \item{abstract_inverted_index.monthly}{}
#'   \item{abstract_inverted_index.statistical}{}
#'   \item{abstract_inverted_index.indicators}{}
#'   \item{abstract_inverted_index.correlation}{}
#'   \item{abstract_inverted_index.consistently}{}
#'   \item{abstract_inverted_index.Overall,}{}
#'   \item{abstract_inverted_index.country}{}
#'   \item{abstract_inverted_index.type}{}
#'   \item{abstract_inverted_index.time.}{}
#'   \item{abstract_inverted_index.technical}{}
#'   \item{abstract_inverted_index.paper}{}
#'   \item{abstract_inverted_index.researchers}{}
#'   \item{abstract_inverted_index.demonstrated}{}
#'   \item{abstract_inverted_index.irrigated}{}
#'   \item{abstract_inverted_index.Specifically,}{}
#'   \item{abstract_inverted_index.nine}{}
#'   \item{abstract_inverted_index.30}{}
#'   \item{abstract_inverted_index.tested}{}
#'   \item{abstract_inverted_index.individually}{}
#'   \item{abstract_inverted_index.obtained}{}
#'   \item{abstract_inverted_index.years,}{}
#'   \item{abstract_inverted_index.applicable}{}
#'   \item{abstract_inverted_index.oxygen}{}
#'   \item{abstract_inverted_index.effluent}{}
#'   \item{abstract_inverted_index.secondary}{}
#'   \item{abstract_inverted_index.costs}{}
#'   \item{abstract_inverted_index.still}{}
#'   \item{abstract_inverted_index.promising}{}
#'   \item{abstract_inverted_index.reports}{}
#'   \item{abstract_inverted_index.)}{}
#'   \item{abstract_inverted_index.installed}{}
#'   \item{abstract_inverted_index.months}{}
#'   \item{abstract_inverted_index.measured}{}
#'   \item{abstract_inverted_index.evaluation}{}
#'   \item{abstract_inverted_index.show}{}
#'   \item{abstract_inverted_index.nearly}{}
#'   \item{abstract_inverted_index.desired}{}
#'   \item{abstract_inverted_index.target}{}
#'   \item{abstract_inverted_index.varying}{}
#'   \item{abstract_inverted_index.measurement}{}
#'   \item{abstract_inverted_index.share}{}
#'   \item{abstract_inverted_index.There}{}
#'   \item{abstract_inverted_index.waters,}{}
#'   \item{abstract_inverted_index.detection}{}
#'   \item{abstract_inverted_index.quantified}{}
#'   \item{abstract_inverted_index.timely}{}
#'   \item{abstract_inverted_index.waters.}{}
#'   \item{abstract_inverted_index.largely}{}
#'   \item{abstract_inverted_index.governance,}{}
#'   \item{abstract_inverted_index.management.}{}
#'   \item{abstract_inverted_index.learn}{}
#'   \item{abstract_inverted_index.enabling}{}
#'   \item{abstract_inverted_index.Kenya.}{}
#'   \item{abstract_inverted_index.below}{}
#'   \item{abstract_inverted_index.Furthermore,}{}
#'   \item{abstract_inverted_index.Escherichia}{}
#'   \item{abstract_inverted_index.samples,}{}
#'   \item{abstract_inverted_index.3)}{}
#'   \item{abstract_inverted_index.detected.}{}
#'   \item{abstract_inverted_index.They}{}
#'   \item{abstract_inverted_index.together}{}
#'   \item{abstract_inverted_index.driven}{}
#'   \item{abstract_inverted_index.rapid}{}
#'   \item{abstract_inverted_index.calls}{}
#'   \item{abstract_inverted_index.efforts.}{}
#'   \item{abstract_inverted_index.reliable}{}
#'   \item{abstract_inverted_index.international}{}
#'   \item{abstract_inverted_index.national}{}
#'   \item{abstract_inverted_index.improvements}{}
#'   \item{abstract_inverted_index.underlying}{}
#'   \item{abstract_inverted_index.map}{}
#'   \item{abstract_inverted_index.implemented}{}
#'   \item{abstract_inverted_index.restoration}{}
#'   \item{abstract_inverted_index.interconnected}{}
#'   \item{abstract_inverted_index.directly}{}
#'   \item{abstract_inverted_index.opportunity}{}
#'   \item{abstract_inverted_index.driving}{}
#'   \item{abstract_inverted_index.vision}{}
#'   \item{abstract_inverted_index.free}{}
#'   \item{abstract_inverted_index.known}{}
#'   \item{abstract_inverted_index.parts}{}
#'   \item{abstract_inverted_index.temperature,}{}
#'   \item{abstract_inverted_index.All}{}
#'   \item{abstract_inverted_index.residence}{}
#'   \item{abstract_inverted_index.culture}{}
#'   \item{abstract_inverted_index.aeruginosa}{}
#'   \item{abstract_inverted_index.storage}{}
#'   \item{abstract_inverted_index.bacteria}{}
#'   \item{abstract_inverted_index.presence}{}
#'   \item{abstract_inverted_index.genome}{}
#'   \item{abstract_inverted_index.Despite}{}
#'   \item{abstract_inverted_index.pit}{}
#'   \item{abstract_inverted_index.latrines}{}
#'   \item{abstract_inverted_index.understood.}{}
#'   \item{abstract_inverted_index.characterized}{}
#'   \item{abstract_inverted_index.sludge}{}
#'   \item{abstract_inverted_index.surveys}{}
#'   \item{abstract_inverted_index.contain}{}
#'   \item{abstract_inverted_index.area.}{}
#'   \item{abstract_inverted_index.degradation}{}
#'   \item{abstract_inverted_index.maintenance}{}
#'   \item{abstract_inverted_index.governments}{}
#'   \item{abstract_inverted_index.released}{}
#'   \item{abstract_inverted_index.promote}{}
#'   \item{abstract_inverted_index.actors}{}
#'   \item{abstract_inverted_index.assigned}{}
#'   \item{abstract_inverted_index.93}{}
#'   \item{abstract_inverted_index.influences}{}
#'   \item{abstract_inverted_index.formal}{}
#'   \item{abstract_inverted_index.align}{}
#'   \item{abstract_inverted_index.recommend}{}
#'   \item{abstract_inverted_index.expand}{}
#'   \item{abstract_inverted_index.shift}{}
#'   \item{abstract_inverted_index.Water,}{}
#'   \item{abstract_inverted_index.attributable}{}
#'   \item{abstract_inverted_index.operation}{}
#'   \item{abstract_inverted_index.trained}{}
#'   \item{abstract_inverted_index.staff}{}
#'   \item{abstract_inverted_index.sustain}{}
#'   \item{abstract_inverted_index.guidelines}{}
#'   \item{abstract_inverted_index.accountability}{}
#'   \item{abstract_inverted_index.order}{}
#'   \item{abstract_inverted_index.enhanced}{}
#'   \item{abstract_inverted_index.zero}{}
#'   \item{abstract_inverted_index.operator}{}
#'   \item{abstract_inverted_index.reaching}{}
#'   \item{abstract_inverted_index.sectors}{}
#'   \item{abstract_inverted_index.relationships}{}
#'   \item{abstract_inverted_index.formation}{}
#'   \item{abstract_inverted_index.clustering}{}
#'   \item{abstract_inverted_index.contrast,}{}
#'   \item{abstract_inverted_index.Multiple}{}
#'   \item{abstract_inverted_index.compounds}{}
#'   \item{abstract_inverted_index.containing}{}
#'   \item{abstract_inverted_index.Further}{}
#'   \item{abstract_inverted_index.investigation}{}
#'   \item{abstract_inverted_index.late}{}
#'   \item{abstract_inverted_index.summer}{}
#'   \item{abstract_inverted_index.provides}{}
#'   \item{abstract_inverted_index.exposure}{}
#'   \item{abstract_inverted_index.growth,}{}
#'   \item{abstract_inverted_index.supply,}{}
#'   \item{abstract_inverted_index.ensuring}{}
#'   \item{abstract_inverted_index.quantity}{}
#'   \item{abstract_inverted_index.document}{}
#'   \item{abstract_inverted_index.primarily}{}
#'   \item{abstract_inverted_index.Environmental}{}
#'   \item{abstract_inverted_index.First,}{}
#'   \item{abstract_inverted_index.organic}{}
#'   \item{abstract_inverted_index.matter}{}
#'   \item{abstract_inverted_index.sewage}{}
#'   \item{abstract_inverted_index.operations.}{}
#'   \item{abstract_inverted_index.When}{}
#'   \item{abstract_inverted_index.civil}{}
#'   \item{abstract_inverted_index.linked}{}
#'   \item{abstract_inverted_index.examining}{}
#'   \item{abstract_inverted_index.contribute}{}
#'   \item{abstract_inverted_index.predictors}{}
#'   \item{abstract_inverted_index.sanitation.}{}
#'   \item{abstract_inverted_index.Based}{}
#'   \item{abstract_inverted_index.research.}{}
#'   \item{abstract_inverted_index.Ghana}{}
#'   \item{abstract_inverted_index.prevalence}{}
#'   \item{abstract_inverted_index.piped}{}
#'   \item{abstract_inverted_index.third}{}
#'   \item{abstract_inverted_index.open}{}
#'   \item{abstract_inverted_index.members}{}
#'   \item{abstract_inverted_index.Key}{}
#'   \item{abstract_inverted_index.themes}{}
#'   \item{abstract_inverted_index.1)}{}
#'   \item{abstract_inverted_index.2)}{}
#'   \item{abstract_inverted_index.city.}{}
#'   \item{abstract_inverted_index.loads}{}
#'   \item{abstract_inverted_index.Bay}{}
#'   \item{abstract_inverted_index.60%}{}
#'   \item{abstract_inverted_index.shorter}{}
#'   \item{abstract_inverted_index.median}{}
#'   \item{abstract_inverted_index.does}{}
#'   \item{abstract_inverted_index.detectable}{}
#'   \item{abstract_inverted_index.contamination}{}
#'   \item{abstract_inverted_index.infiltration}{}
#'   \item{abstract_inverted_index.recharge}{}
#'   \item{abstract_inverted_index.groundwater,}{}
#'   \item{abstract_inverted_index.makes}{}
#'   \item{abstract_inverted_index.conduct}{}
#'   \item{abstract_inverted_index.upstream}{}
#'   \item{abstract_inverted_index.threats}{}
#'   \item{abstract_inverted_index.activities,}{}
#'   \item{abstract_inverted_index.following}{}
#'   \item{abstract_inverted_index.uncertainty}{}
#'   \item{abstract_inverted_index.urbanized}{}
#'   \item{abstract_inverted_index.air}{}
#'   \item{abstract_inverted_index.whereas}{}
#'   \item{abstract_inverted_index.constant}{}
#'   \item{abstract_inverted_index.years.}{}
#'   \item{abstract_inverted_index.useful}{}
#'   \item{abstract_inverted_index.conditions.}{}
#'   \item{abstract_inverted_index.practitioners}{}
#'   \item{abstract_inverted_index.rely}{}
#'   \item{abstract_inverted_index.rainwater}{}
#'   \item{abstract_inverted_index.presents}{}
#'   \item{abstract_inverted_index.collection}{}
#'   \item{abstract_inverted_index.intervention}{}
#'   \item{abstract_inverted_index.completed}{}
#'   \item{abstract_inverted_index.11%}{}
#'   \item{abstract_inverted_index.remained}{}
#'   \item{abstract_inverted_index.provision}{}
#'   \item{abstract_inverted_index.locally}{}
#'   \item{abstract_inverted_index.countries.}{}
#'   \item{abstract_inverted_index.second}{}
#'   \item{abstract_inverted_index.site}{}
#'   \item{abstract_inverted_index.explored}{}
#'   \item{abstract_inverted_index.interactive}{}
#'   \item{abstract_inverted_index.intensity}{}
#'   \item{abstract_inverted_index.Understanding}{}
#'   \item{abstract_inverted_index.subsequent}{}
#'   \item{abstract_inverted_index.flows}{}
#'   \item{abstract_inverted_index.detailed}{}
#'   \item{abstract_inverted_index.watersheds}{}
#'   \item{abstract_inverted_index.Upper}{}
#'   \item{abstract_inverted_index.dissolved}{}
#'   \item{abstract_inverted_index.Colorado}{}
#'   \item{abstract_inverted_index.previously}{}
#'   \item{abstract_inverted_index.protection}{}
#'   \item{abstract_inverted_index.maximum}{}
#'   \item{abstract_inverted_index.contaminant}{}
#'   \item{abstract_inverted_index.participatory}{}
#'   \item{abstract_inverted_index.gender}{}
#'   \item{abstract_inverted_index.Cambodia}{}
#'   \item{abstract_inverted_index.program}{}
#'   \item{abstract_inverted_index.reflect}{}
#'   \item{abstract_inverted_index.extent}{}
#'   \item{abstract_inverted_index.indicate}{}
#'   \item{abstract_inverted_index.engaging}{}
#'   \item{abstract_inverted_index.supporting}{}
#'   \item{abstract_inverted_index.derived}{}
#'   \item{abstract_inverted_index.sector,}{}
#'   \item{abstract_inverted_index.investigate}{}
#'   \item{abstract_inverted_index.adoption}{}
#'   \item{abstract_inverted_index.aged}{}
#'   \item{abstract_inverted_index.children}{}
#'   \item{abstract_inverted_index.facilities.}{}
#'   \item{abstract_inverted_index.Developing}{}
#'   \item{abstract_inverted_index.journal}{}
#'   \item{abstract_inverted_index.articles}{}
#'   \item{abstract_inverted_index.last}{}
#'   \item{abstract_inverted_index.height}{}
#'   \item{abstract_inverted_index.worldwide}{}
#'   \item{abstract_inverted_index.offers}{}
#'   \item{abstract_inverted_index.dynamic}{}
#'   \item{abstract_inverted_index.areas,}{}
#'   \item{abstract_inverted_index.magnitude}{}
#'   \item{abstract_inverted_index.widely}{}
#'   \item{abstract_inverted_index.humanitarian}{}
#'   \item{abstract_inverted_index.Research}{}
#'   \item{abstract_inverted_index.online}{}
#'   \item{abstract_inverted_index.score}{}
#'   \item{abstract_inverted_index.according}{}
#'   \item{abstract_inverted_index.experts}{}
#'   \item{abstract_inverted_index.evaluating}{}
#'   \item{abstract_inverted_index.contexts.}{}
#'   \item{abstract_inverted_index.priorities.}{}
#'   \item{abstract_inverted_index.21}{}
#'   \item{abstract_inverted_index.means}{}
#'   \item{abstract_inverted_index.parameters,}{}
#'   \item{abstract_inverted_index.interest}{}
#'   \item{abstract_inverted_index.insecurity.}{}
#'   \item{abstract_inverted_index.semi-arid}{}
#'   \item{abstract_inverted_index.insecurity}{}
#'   \item{abstract_inverted_index.dry}{}
#'   \item{abstract_inverted_index.techniques.}{}
#'   \item{abstract_inverted_index.Given}{}
#'   \item{abstract_inverted_index.offer}{}
#'   \item{abstract_inverted_index.prioritize}{}
#'   \item{abstract_inverted_index.risks,}{}
#'   \item{abstract_inverted_index.filters}{}
#'   \item{abstract_inverted_index.incidence}{}
#'   \item{abstract_inverted_index.designed}{}
#'   \item{abstract_inverted_index.risk.}{}
#'   \item{abstract_inverted_index.Local}{}
#'   \item{abstract_inverted_index.coordination}{}
#'   \item{abstract_inverted_index.use,}{}
#'   \item{abstract_inverted_index.isotope}{}
#'   \item{abstract_inverted_index.(i.e.,}{}
#'   \item{abstract_inverted_index.H}{}
#'   \item{abstract_inverted_index.seasons}{}
#'   \item{abstract_inverted_index.validated}{}
#'   \item{abstract_inverted_index.annually}{}
#'   \item{abstract_inverted_index.wells}{}
#'   \item{abstract_inverted_index.reliability}{}
#'   \item{abstract_inverted_index.overcome}{}
#'   \item{abstract_inverted_index.households,}{}
#'   \item{abstract_inverted_index.women}{}
#'   \item{abstract_inverted_index.safely}{}
#'   \item{abstract_inverted_index.managed}{}
#'   \item{abstract_inverted_index.Although}{}
#'   \item{abstract_inverted_index.establishing}{}
#'   \item{abstract_inverted_index.divided}{}
#'   \item{abstract_inverted_index.±}{}
#'   \item{abstract_inverted_index.12}{}
#'   \item{abstract_inverted_index.9}{}
#'   \item{abstract_inverted_index.15}{}
#'   \item{abstract_inverted_index.winter}{}
#'   \item{abstract_inverted_index.farmers}{}
#'   \item{abstract_inverted_index.actual}{}
#'   \item{abstract_inverted_index.operated}{}
#'   \item{abstract_inverted_index.northern}{}
#'   \item{abstract_inverted_index.arsenic}{}
#'   \item{abstract_inverted_index.presented}{}
#'   \item{abstract_inverted_index.ranged}{}
#'   \item{abstract_inverted_index.limits}{}
#'   \item{abstract_inverted_index.60}{}
#'   \item{abstract_inverted_index.sampled}{}
#'   \item{abstract_inverted_index.former}{}
#'   \item{abstract_inverted_index.wellbeing.}{}
#'   \item{abstract_inverted_index.year,}{}
#'   \item{abstract_inverted_index.dataset}{}
#'   \item{abstract_inverted_index.suggesting}{}
#'   \item{abstract_inverted_index.fully}{}
#'   \item{abstract_inverted_index.San}{}
#'   \item{abstract_inverted_index.Out}{}
#'   \item{abstract_inverted_index.disposal}{}
#'   \item{abstract_inverted_index.waterborne}{}
#'   \item{abstract_inverted_index.(e.g.}{}
#'   \item{abstract_inverted_index.practices,}{}
#'   \item{abstract_inverted_index.volume}{}
#'   \item{abstract_inverted_index.passive}{}
#'   \item{abstract_inverted_index.coupled}{}
#'   \item{abstract_inverted_index.faecal}{}
#'   \item{abstract_inverted_index.indicator}{}
#'   \item{abstract_inverted_index.contexts}{}
#'   \item{abstract_inverted_index.real-time}{}
#'   \item{abstract_inverted_index.achieving}{}
#'   \item{abstract_inverted_index.undertaken}{}
#'   \item{abstract_inverted_index.First}{}
#'   \item{abstract_inverted_index.approaches,}{}
#'   \item{abstract_inverted_index.planetary}{}
#'   \item{abstract_inverted_index.salinity}{}
#'   \item{abstract_inverted_index.resulted}{}
#'   \item{abstract_inverted_index.16S}{}
#'   \item{abstract_inverted_index.rRNA}{}
#'   \item{abstract_inverted_index.gene}{}
#'   \item{abstract_inverted_index.prioritized}{}
#'   \item{abstract_inverted_index.levels.}{}
#'   \item{abstract_inverted_index.prevent}{}
#'   \item{abstract_inverted_index.fish}{}
#'   \item{abstract_inverted_index.site.}{}
#'   \item{abstract_inverted_index.removal}{}
#'   \item{abstract_inverted_index.pH}{}
#'   \item{abstract_inverted_index.confirmed}{}
#'   \item{abstract_inverted_index.possibly}{}
#'   \item{abstract_inverted_index.leaves}{}
#'   \item{abstract_inverted_index.September}{}
#'   \item{abstract_inverted_index.socially}{}
#'   \item{abstract_inverted_index.consumption}{}
#'   \item{abstract_inverted_index.linear}{}
#'   \item{abstract_inverted_index.explain}{}
#'   \item{abstract_inverted_index.until}{}
#'   \item{abstract_inverted_index.outcomes,}{}
#'   \item{abstract_inverted_index.required.}{}
#'   \item{abstract_inverted_index.regulatory}{}
#'   \item{abstract_inverted_index.adopted}{}
#'   \item{abstract_inverted_index.connections}{}
#'   \item{abstract_inverted_index.occur}{}
#'   \item{abstract_inverted_index.short-term}{}
#'   \item{abstract_inverted_index.wells.}{}
#'   \item{abstract_inverted_index.(including}{}
#'   \item{abstract_inverted_index.Both}{}
#'   \item{abstract_inverted_index.events}{}
#'   \item{abstract_inverted_index.contaminated}{}
#'   \item{abstract_inverted_index.worked}{}
#'   \item{abstract_inverted_index.knowledges}{}
#'   \item{abstract_inverted_index.collaborative}{}
#'   \item{abstract_inverted_index.central}{}
#'   \item{abstract_inverted_index.climatic}{}
#'   \item{abstract_inverted_index.outcome}{}
#'   \item{abstract_inverted_index.settings,}{}
#'   \item{abstract_inverted_index.extract}{}
#'   \item{abstract_inverted_index.production,}{}
#'   \item{abstract_inverted_index.comparison}{}
#'   \item{abstract_inverted_index.tank}{}
#'   \item{abstract_inverted_index.log}{}
#'   \item{abstract_inverted_index.samples.}{}
#'   \item{abstract_inverted_index.Therefore,}{}
#'   \item{abstract_inverted_index.wetland}{}
#'   \item{abstract_inverted_index.Cl}{}
#'   \item{abstract_inverted_index.months,}{}
#'   \item{abstract_inverted_index.rapidly}{}
#'   \item{abstract_inverted_index.identification}{}
#'   \item{abstract_inverted_index.hundreds}{}
#'   \item{abstract_inverted_index.short}{}
#'   \item{abstract_inverted_index.coming}{}
#'   \item{abstract_inverted_index.always}{}
#'   \item{abstract_inverted_index.demand,}{}
#'   \item{abstract_inverted_index.cholera}{}
#'   \item{abstract_inverted_index.Sanitation}{}
#'   \item{abstract_inverted_index.successful}{}
#'   \item{abstract_inverted_index.users,}{}
#'   \item{abstract_inverted_index.Four}{}
#'   \item{abstract_inverted_index.stakeholder}{}
#'   \item{abstract_inverted_index.engage}{}
#'   \item{abstract_inverted_index.future.}{}
#' }
"ploswater"
